### ISSUE TITLE
Failed to build Image 

### ISSUE THREAD

**Issue by downright-ux** [fsphys/sogo-keycloak-docker-example#1] opened 2022-10-04 02:12 UTC
When executing docker compose up -d I got the following.
```
failed to solve: executor failed running [/bin/sh -c apt-get update  && apt-get install -y gnupg apt-transport-https ca-certificates         supervisor nginx  && apt-key adv --keyserver hkp://keys.gnupg.net --recv-key 0x810273C4  && echo "deb https://packages.inverse.ca/SOGo/nightly/5/ubuntu/ focal focal" > /etc/apt/sources.list.d/SOGo.list  && apt-get update  && ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime  && mkdir -p /usr/share/doc/sogo/ && touch /usr/share/doc/sogo/stub.sh  && apt-get install -y sogo sope4.9-gdl1-postgresql  && apt-get clean && rm -rf /var/lib/apt/lists/*]: exit code: 2
```
OS PopOS 22.04

Docker Information
```
Client: Docker Engine - Community
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:46 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:00:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by AlexanderKaschta** [comment] 2023-08-22 10:14
The issue is, that SOGo changed the url to their package repository and therefore our uploaded version isn't working any more. This is also partly due to the reason, that the project got bought by another company and ownership changed.

There is an easy fix for this: Go to https://www.sogo.nu/download.html , select the latest nightly build version 5 for Ubuntu 20.04 or 22.04 and update the `tee` command with the correct url. This should make it work. (Yes, we've also have it already running on Ubuntu 22.04 working perfectly).

We'll archive this repository soon as it's only reason was to provide a minimal, reproducible example setup to file a bug in SOGo with SAML SSO.

**Closed as completed by AlexanderKaschta** 2023-08-22 10:14 UTC
